# Generated by Django 4.1.7 on 2023-04-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
